// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestTextEditor
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Cut the selected Text from the Screen
        /// </summary>
        public void CutAction()
        {
            #region Variable Declarations
            WinEdit uIRTBEdit = this.UITextEditorWindow.UIRTBWindow.UIRTBEdit;
            WinMenuItem uIEditMenuItem = this.UITextEditorWindow.UIMenuStrip1MenuBar.UIEditMenuItem;
            WinMenuItem uICutMenuItem = this.UITextEditorWindow.UIMenuStrip1MenuBar.UIEditMenuItem.UICutMenuItem;
            #endregion

            // The recording for the application under test '\\obs-lancia\students\arya1516\TextEditor\TextEditor\bin\Debug\TextEditor.vshost.exe' may not be correct as it is located on a network share. Please install the application on a local path.

            // Type 'Hello ' in 'RTB' text box
            uIRTBEdit.Text = this.CutActionParams.UIRTBEditText;

            // Type '{LShiftKey}' in 'RTB' text box
            Keyboard.SendKeys(uIRTBEdit, this.CutActionParams.UIRTBEditSendKeys, ModifierKeys.None);

            // Click 'Edit' menu item
            Mouse.Click(uIEditMenuItem, new Point(8, 10));

            // Click 'RTB' text box
            Mouse.Click(uIRTBEdit, new Point(29, 4));

            // Move 'RTB' text box
            Mouse.StartDragging(uIRTBEdit, new Point(29, 11));
            Mouse.StopDragging(uIRTBEdit, -28, 3);

            // Click 'Edit' -> 'Cut' menu item
            Mouse.Click(uICutMenuItem, new Point(25, 6));
        }
        
        #region Properties
        public virtual CutActionParams CutActionParams
        {
            get
            {
                if ((this.mCutActionParams == null))
                {
                    this.mCutActionParams = new CutActionParams();
                }
                return this.mCutActionParams;
            }
        }
        
        public UITextEditorWindow UITextEditorWindow
        {
            get
            {
                if ((this.mUITextEditorWindow == null))
                {
                    this.mUITextEditorWindow = new UITextEditorWindow();
                }
                return this.mUITextEditorWindow;
            }
        }
        #endregion
        
        #region Fields
        private CutActionParams mCutActionParams;
        
        private UITextEditorWindow mUITextEditorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CutAction'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class CutActionParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Hello ' in 'RTB' text box
        /// </summary>
        public string UIRTBEditText = "Hello ";
        
        /// <summary>
        /// Type '{LShiftKey}' in 'RTB' text box
        /// </summary>
        public string UIRTBEditSendKeys = "{LShiftKey}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITextEditorWindow : WinWindow
    {
        
        public UITextEditorWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "TextEditor";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("TextEditor");
            #endregion
        }
        
        #region Properties
        public UIRTBWindow UIRTBWindow
        {
            get
            {
                if ((this.mUIRTBWindow == null))
                {
                    this.mUIRTBWindow = new UIRTBWindow(this);
                }
                return this.mUIRTBWindow;
            }
        }
        
        public UIMenuStrip1MenuBar UIMenuStrip1MenuBar
        {
            get
            {
                if ((this.mUIMenuStrip1MenuBar == null))
                {
                    this.mUIMenuStrip1MenuBar = new UIMenuStrip1MenuBar(this);
                }
                return this.mUIMenuStrip1MenuBar;
            }
        }
        #endregion
        
        #region Fields
        private UIRTBWindow mUIRTBWindow;
        
        private UIMenuStrip1MenuBar mUIMenuStrip1MenuBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIRTBWindow : WinWindow
    {
        
        public UIRTBWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "RTB";
            this.WindowTitles.Add("TextEditor");
            #endregion
        }
        
        #region Properties
        public WinEdit UIRTBEdit
        {
            get
            {
                if ((this.mUIRTBEdit == null))
                {
                    this.mUIRTBEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIRTBEdit.WindowTitles.Add("TextEditor");
                    #endregion
                }
                return this.mUIRTBEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIRTBEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMenuStrip1MenuBar : WinMenuBar
    {
        
        public UIMenuStrip1MenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "menuStrip1";
            this.WindowTitles.Add("TextEditor");
            #endregion
        }
        
        #region Properties
        public UIEditMenuItem UIEditMenuItem
        {
            get
            {
                if ((this.mUIEditMenuItem == null))
                {
                    this.mUIEditMenuItem = new UIEditMenuItem(this);
                }
                return this.mUIEditMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIEditMenuItem mUIEditMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIEditMenuItem : WinMenuItem
    {
        
        public UIEditMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Edit";
            this.WindowTitles.Add("TextEditor");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UICutMenuItem
        {
            get
            {
                if ((this.mUICutMenuItem == null))
                {
                    this.mUICutMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUICutMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Cut";
                    this.mUICutMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUICutMenuItem.WindowTitles.Add("TextEditor");
                    #endregion
                }
                return this.mUICutMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUICutMenuItem;
        #endregion
    }
}
